In [1]:
%matplotlib inline

# PyTorch
It's a Python based scientific computing package targeted at two sets of audiences.
* A replacement for NumPy to use the power of GPUs.
* A deep learning research platform that provides maximum flexibility and speed.

## Getting Started
Tensors<br>
Tensors are similar to NumPy's ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.

In [2]:
from __future__ import print_function
import torch

##### 1.Construct a 5*3 matrix, uninitialized.

In [3]:
x = torch.empty(5,3)    # Creating a empty tensor of size 5*3.
# We will get values already existing in the memory i.e., some garbage values
print(x)

tensor([[1.9349e-19, 4.5445e+30, 4.7429e+30],
        [7.1354e+31, 7.1118e-04, 1.7444e+28],
        [7.3909e+22, 4.5828e+30, 3.2483e+33],
        [1.9690e-19, 6.8589e+22, 1.3340e+31],
        [1.1708e-19, 7.2128e+22, 9.2216e+29]])


##### 2.Construct a randomly initialized  matrix.

In [4]:
x = torch.rand(5,3)  # Creating a tensor with random values ranging from 0 to 1
print(x)

tensor([[0.9247, 0.5996, 0.2167],
        [0.6869, 0.0403, 0.2887],
        [0.1835, 0.5055, 0.1264],
        [0.9347, 0.5936, 0.5389],
        [0.9924, 0.9569, 0.5236]])


##### 3.Construct a matrix filled zeros and dtype long.

In [5]:
x = torch.zeros(5,3, dtype = torch.long)  # Creating a tensor with 0 values and dtype as long. 
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


##### 4.Construct a tensor directly from data.

In [6]:
x = torch.tensor([5,5,3]) # Creating a tensor with values [5,5,3]
print(x)

tensor([5, 5, 3])


##### or create a tensor based on a existing tensor. These methods will reuse properties of the input tensor,e.g. dtype,unless new values are provided by the user.

In [7]:
x = x.new_ones(5,3,dtype=torch.double)     # new_* methods take in sizes.
print(x)

y = torch.randn_like(x, dtype=torch.float)  # *_like methods
# The above code overrides dtype!
print(y)                                   # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.4285, -0.5936, -0.9010],
        [ 0.4620,  0.8481, -0.2819],
        [ 0.7065, -0.7924,  0.9688],
        [ 1.3460,  0.7535,  0.9499],
        [ 0.2453, -0.3622, -1.5017]])


##### 5.Get it's size

In [8]:
print(x.size())
print(y.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [9]:
s = x.size()
print(s[0])
print(s[1])

5
3


<br>
Note <br>
"torch.size" is in fact a tuple, so it supports all tuple operations.<br>
Operations<br>
There are multiple syntaxes for the operations.In the following example, we will take a look at the addition operation.
<br><br>
Addition: syntax 1

In [10]:
y = torch.rand(5,3)
print(x+y)

tensor([[1.0621, 1.7502, 1.6451],
        [1.4450, 1.9086, 1.2129],
        [1.9460, 1.8682, 1.3145],
        [1.4709, 1.9640, 1.3083],
        [1.0486, 1.8586, 1.1142]], dtype=torch.float64)


<br>
Addition: syntax 2

In [11]:
print(torch.add(x,y))

tensor([[1.0621, 1.7502, 1.6451],
        [1.4450, 1.9086, 1.2129],
        [1.9460, 1.8682, 1.3145],
        [1.4709, 1.9640, 1.3083],
        [1.0486, 1.8586, 1.1142]], dtype=torch.float64)


<br>
Addition: providing an output tensor as argument

In [12]:
result = torch.empty(5,3)
torch.add(x, y, out=result)
print(result)

tensor([[1.0621, 1.7502, 1.6451],
        [1.4450, 1.9086, 1.2129],
        [1.9460, 1.8682, 1.3145],
        [1.4709, 1.9640, 1.3083],
        [1.0486, 1.8586, 1.1142]])


<br>
Addition: in-place

In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[1.0621, 1.7502, 1.6451],
        [1.4450, 1.9086, 1.2129],
        [1.9460, 1.8682, 1.3145],
        [1.4709, 1.9640, 1.3083],
        [1.0486, 1.8586, 1.1142]])


<br>Note<br>
Any operation thet mutates a tensor in-place is post-fixed with an "_". For example "x.copy_(y)", "x.t_()" will change "x".<br><br>
You can use standard NumPy-like indexing with all bells and whistles!

In [14]:
print(y)
print(y[:,1])

tensor([[1.0621, 1.7502, 1.6451],
        [1.4450, 1.9086, 1.2129],
        [1.9460, 1.8682, 1.3145],
        [1.4709, 1.9640, 1.3083],
        [1.0486, 1.8586, 1.1142]])
tensor([1.7502, 1.9086, 1.8682, 1.9640, 1.8586])


<br>Resizing: If you want to resize/reshape tensor, you can use torch. view

In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)    # the size -1 is inferred from other dimensions.
q = x.view(2,2,-1)
print(x.size() , y.size(), z.size(),q.size(),'\n')
print(x,'\n\n',y,'\n\n',z,'\n\n',q)

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8]) torch.Size([2, 2, 4]) 

tensor([[-1.3970, -1.6955,  1.3494,  1.5037],
        [ 1.8218, -0.2961, -1.8839, -1.4941],
        [-0.3808,  0.8399, -0.6117,  1.3475],
        [ 0.6931,  1.8317, -0.1227,  0.5390]]) 

 tensor([-1.3970, -1.6955,  1.3494,  1.5037,  1.8218, -0.2961, -1.8839, -1.4941,
        -0.3808,  0.8399, -0.6117,  1.3475,  0.6931,  1.8317, -0.1227,  0.5390]) 

 tensor([[-1.3970, -1.6955,  1.3494,  1.5037,  1.8218, -0.2961, -1.8839, -1.4941],
        [-0.3808,  0.8399, -0.6117,  1.3475,  0.6931,  1.8317, -0.1227,  0.5390]]) 

 tensor([[[-1.3970, -1.6955,  1.3494,  1.5037],
         [ 1.8218, -0.2961, -1.8839, -1.4941]],

        [[-0.3808,  0.8399, -0.6117,  1.3475],
         [ 0.6931,  1.8317, -0.1227,  0.5390]]])


<br><br>
If you have a one element tensor, use .item() to get the value as a Python number

In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.6624])
-0.6624211668968201


##### Read later: <br>
100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc., are described here<br>
<http://pytorch.org/docs/torch>

## NumPy Bridge
Converting a Torch Tensor to a NumPy array and vice versa is a breeze.<br>
The Torch Tensor and NumPy array will share their underlying memory locations, and changing one will change the other.<br><br>
Converting a Torch Tensor to a NumPy Array

In [17]:
a = torch.ones(5)
print(a,type(a))

tensor([1., 1., 1., 1., 1.]) <class 'torch.Tensor'>


In [18]:
b = a.numpy()
print(b,type(b))

[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>


<br>See how the numpy array changed in value.

In [19]:
a.add_(1)
print(a)
print(b)  # bcoz even it's converted to numPy array,they share same memory

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


<br>Converting NumPy Array to Torch Tensor.<br>
See how changing the np array changed the Torch Tensor automatically

In [20]:
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a,1,out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

### CUDA Tensors
Tensors can be moved onto any device using the .to method.

In [21]:
# let us run this cell only if CUBA is available
# We will use  ''torch.device'' objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")           # a CUDA device object
    y = torch.ones_like(x, device=device)   # directly create a tensor on GPU
    x = x.to(device)                        # or just use strings ''.to("cuba")''
    z = x+y
    print(z)
    print(z.to("cpu",torch.double))        # ''.to'' can also change dtype together!

In [22]:
torch.cuda.is_available()  # checking if a GPU is allocated or not.

False