# NumPy - Numerical Python
It is used for numerical operations realated to Linear algebra and calculus.

## Understanding Dimensionality and Shape

In [6]:
import numpy as np

In [7]:
l = [1,2,3]

x1 = np.array(l)
print(type(x1),x1)

<class 'numpy.ndarray'> [1 2 3]


In [9]:
print("Dimentionality of the numpy array : ",x1.ndim) # gives no of nested brackets in the numPy array
print("Shape of the numpy array : ",x1.shape)  # gives the shape each and every dimension

Dimentionality of the numpy array :  1
Shape of the numpy array :  (3,)


In [10]:
x2 = np.array( [ [1] , [2] , [3] ] )
print(x2)
print("Dimentionality of the numpy array : ",x2.ndim) # gives no of nested brackets in the numPy array
print("Shape of the numpy array : ",x2.shape)  # gives the shape each and every dimension

[[1]
 [2]
 [3]]
Dimentionality of the numpy array :  2
Shape of the numpy array :  (3, 1)


In [1]:
import numpy as np
x2 = np.array([[10,9,8],[7,6,5],[4,3,2]])
resized_matrix = np.resize(x2,(6,2))       # Resizing the matrix
print(resized_matrix)
print(x2)
print("Dimentionality of the numpy array : ",x2.ndim) # gives no of nested brackets in the numPy array
print("Shape of the numpy array : ",x2.shape)  # gives the shape each and every dimension

[[10  9]
 [ 8  7]
 [ 6  5]
 [ 4  3]
 [ 2 10]
 [ 9  8]]
[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]
Dimentionality of the numpy array :  2
Shape of the numpy array :  (3, 3)


In [5]:
help(np.resize)

Help on function resize in module numpy:

resize(a, new_shape)
    Return a new array with the specified shape.
    
    If the new array is larger than the original array, then the new
    array is filled with repeated copies of `a`.  Note that this behavior
    is different from a.resize(new_shape) which fills with zeros instead
    of repeated copies of `a`.
    
    Parameters
    ----------
    a : array_like
        Array to be resized.
    
    new_shape : int or tuple of int
        Shape of resized array.
    
    Returns
    -------
    reshaped_array : ndarray
        The new array is formed from the data in the old array, repeated
        if necessary to fill out the required number of elements.  The
        data are repeated in the order that they are stored in memory.
    
    See Also
    --------
    ndarray.resize : resize an array in-place.
    
    Notes
    -----
    i.e. it does not apply interpolation/extrapolation.
    It fills the return array with the required 

In [6]:
x3 = np.array([[[1,2,10],[3,4,20]],[[5,6,30],[7,8,40]]])

print(x3)
print("Dimentionality of the numpy array : ",x3.ndim) # gives no of nested brackets in the numPy array
print("Shape of the numpy array : ",x3.shape)  # gives the shape each and every dimension

[[[ 1  2 10]
  [ 3  4 20]]

 [[ 5  6 30]
  [ 7  8 40]]]
Dimentionality of the numpy array :  3
Shape of the numpy array :  (2, 2, 3)


## Operations on NumPy arrays

In [7]:
A = np.array([[10,9,8],[7,6,5],[4,3,2]])
B = np.array([[11,22,33],[54,12,10],[5,4,9]])

print(A)
print()
print(B)

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]

[[11 22 33]
 [54 12 10]
 [ 5  4  9]]


In [18]:
print(A + B)  # Addition

[[21 31 41]
 [61 18 15]
 [ 9  7 11]]


In [19]:
print(A - B)  # Subtraction

[[ -1 -13 -25]
 [-47  -6  -5]
 [ -1  -1  -7]]


In [15]:
print(A * B)  # Element-wise Multiplication

[[110 198 264]
 [378  72  50]
 [ 20  12  18]]


In [16]:
print(A / B)  # Element-wise Division

[[0.90909091 0.40909091 0.24242424]
 [0.12962963 0.5        0.5       ]
 [0.8        0.75       0.22222222]]


In [17]:
print(A ^ B)  # Element-wise XOR

[[ 1 31 41]
 [49 10 15]
 [ 1  7 11]]


In [14]:
print(A @ B)  # Matrix multiplication of A and B
# (3,3) @ (3,3) => {3,3}

[[636 360 492]
 [426 246 336]
 [216 132 180]]


In [21]:
print(A)
print()
print(A.T)  # Transpose of A

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]

[[10  7  4]
 [ 9  6  3]
 [ 8  5  2]]


In [27]:
X = np.array([[1,2,3]]) # Row Matrix

print(X,X.shape, '\n')

X_trans = X.T
print(X_trans,X_trans.shape) # Column Matrix

[[1 2 3]] (1, 3) 

[[1]
 [2]
 [3]] (3, 1)


In [29]:
print(A)
print()
print(A.ravel())  # It brings to single dimensional array

[[10  9  8]
 [ 7  6  5]
 [ 4  3  2]]

[10  9  8  7  6  5  4  3  2]


In [30]:
print(B)
print()
print(np.linalg.det(B))   # Determinant of matrix

[[11 22 33]
 [54 12 10]
 [ 5  4  9]]

-3696.0


In [33]:
print(B)
print()

B_inv = np.linalg.inv(B)  # Inverse of a matrix
print(B_inv)
print()

print((B_inv @ B).round(0))  # B @ B_inv = I (Identity matrix)

[[11 22 33]
 [54 12 10]
 [ 5  4  9]]

[[-0.01839827  0.01785714  0.04761905]
 [ 0.11796537  0.01785714 -0.45238095]
 [-0.04220779 -0.01785714  0.28571429]]

[[ 1.  0.  0.]
 [ 0.  1. -0.]
 [ 0.  0.  1.]]


In [35]:
print(np.log(B),'\n')    # element-wise log 
print(np.sin(B),'\n')    # element-wise sin
print(np.tan(B),'\n')    # element-wise tan
print(np.exp(B),'\n')    # element-wise exponentiation

[[2.39789527 3.09104245 3.49650756]
 [3.98898405 2.48490665 2.30258509]
 [1.60943791 1.38629436 2.19722458]] 

[[-0.99999021 -0.00885131  0.99991186]
 [-0.55878905 -0.53657292 -0.54402111]
 [-0.95892427 -0.7568025   0.41211849]] 

[[-2.25950846e+02  8.85165604e-03 -7.53130148e+01]
 [ 6.73800101e-01 -6.35859929e-01  6.48360827e-01]
 [-3.38051501e+00  1.15782128e+00 -4.52315659e-01]] 

[[5.98741417e+04 3.58491285e+09 2.14643580e+14]
 [2.83075330e+23 1.62754791e+05 2.20264658e+04]
 [1.48413159e+02 5.45981500e+01 8.10308393e+03]] 



## Broadcasting in numPy

In [37]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
X = np.array([[1,1,1]])
Y = np.array([[2],[2],[2]])

print(A, A.shape, '\n')
print(X, X.shape, '\n')
print(Y, Y.shape, '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3) 

[[1 1 1]] (1, 3) 

[[2]
 [2]
 [2]] (3, 1) 



In [39]:
print(A + 10)  # 10 will be broadcasted to add to element of A

[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [40]:
print(A + X)  # X will be broadcasted to add to each element of A

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [41]:
print(A + Y) # Y will be broadcasted to add to each element of A

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [42]:
print(X + Y) # Broadcasting of X and Y

[[3 3 3]
 [3 3 3]
 [3 3 3]]


## Other np methods

In [45]:
A = np.arange(10)  # Similar to range function..It take values from 0 to 9
print(A)
print()

print(np.resize(A,(3,3)))

[0 1 2 3 4 5 6 7 8 9]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [51]:
A = np.zeros((2,4))   # Zero matrix of given shape
print(A)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [52]:
I = np.eye(5) # Identity matrix of given size
print(I)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
A = np.random.random((2,2)) # Random values from 0-1 of given shape
print(A)

[[0.1914778  0.31637913]
 [0.83473782 0.94515873]]


#### For more methods of numpy , we can search in numpy.org